### ISSUE TITLE
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./pretrained_models/stable-diffusion-v1-5.

### ISSUE THREAD

**Issue by Kevin-free** [fudan-generative-vision/hallo#119]
after execute `python scripts/inference.py --source_image examples/reference_images/1.jpg --driving_audio examples/driving_audios/1.wav`

output:

```shell
INFO:audio_separator.separator.separator:Separation duration: 00:00:21
Traceback (most recent call last):
  File "/root/hallo/scripts/inference.py", line 376, in <module>
    inference_process(command_line_args)
  File "/root/hallo/scripts/inference.py", line 196, in inference_process
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 632, in from_pretrained
    model_file = _get_model_file(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/utils/hub_utils.py", line 306, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./pretrained_models/stable-diffusion-v1-5.
```

**Comment by AricGamma** [comment]
You can check the `pretrained_models` folder.  Refer to https://github.com/fudan-generative-vision/hallo?tab=readme-ov-file#-download-pretrained-models
![image](https://github.com/fudan-generative-vision/hallo/assets/17402682/3de3b64d-626f-4d95-aecf-32def3f55593)
