### ISSUE TITLE
Diffusers Issue

### ISSUE THREAD

**Issue by ldavis9000aws** [fudan-generative-vision/hallo#205]
I've went through the install and am receiving the following error when I run this command for inference. The "pretrained_models" directory was created and populated without an issue prior to running inference.

python scripts/inference.py --source_image examples/reference_images/1.jpg --driving_audio examples/driving_audios/1.wav

**Traceback (most recent call last):
  File "/home/ubuntu/hallo/scripts/inference.py", line 35, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "/home/ubuntu/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/ubuntu/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/ubuntu/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/ubuntu/miniconda3/envs/hallo/lib/python3.10/site-packages/huggingface_hub/__init__.py)**

Here is my CUBA driver version:

```
(hallo) ubuntu@ip-10-0-12-195:~/hallo$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
(hallo) ubuntu@ip-10-0-12-195:~/hallo$

```
[piplist.txt](https://github.com/user-attachments/files/17651845/piplist.txt)

**Comment by mudassirkhan19** [comment]
Downgrading hf hub should work:
https://github.com/easydiffusion/easydiffusion/issues/1851#issuecomment-2445843321
