### ISSUE TITLE
cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'

### ISSUE THREAD

**Issue by leatherbagemperor** [fudan-generative-vision/hallo#209]
I encountered the following issues during execution：

Traceback (most recent call last):
  File "/Halo/hallo/scripts/inference.py", line 376, in <module>
    inference_process(command_line_args)
  File "/Halo/hallo/scripts/inference.py", line 163, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "/root/anaconda3/envs/hallo/lib/python3.10/site-packages/hallo/datasets/image_processor.py", line 124, in preprocess
    faces = self.face_analysis.get(cv2.cvtColor(np.array(ref_image_pil.copy()), cv2.COLOR_RGB2BGR))
cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
 
appreciate for explaination

**Comment by xumingw** [comment]
Could you check whether ref_image_pil.copy()  is empty?

**Comment by leatherbagemperor** [comment]
sry I'm not sure how to check. ㄒoㄒ
