### ISSUE TITLE
Cant Run Web ui On Pinokio 

### ISSUE THREAD

**Issue by alieverlove** [fudan-generative-vision/hallo#30]
Hallo sir, please help me , When I click Start , This happened 
=======================================
Unable to create process using 'F:\PinokioBrowser\pinokio\bin\miniconda\python.exe F:\PinokioBrowser\pinokio\bin\miniconda\Scripts\conda-script.py shell.cmd.exe activate base '
Traceback (most recent call last):
  File "F:\PinokioBrowser\pinokio\api\hallo.git\app\scripts\app.py", line 1, in <module>
    from inference import inference_process
  File "F:\PinokioBrowser\pinokio\api\hallo.git\app\scripts\inference.py", line 34, in <module>
    import torch
ModuleNotFoundError: No module named 'torch' 
=========================================
![Screenshot 2024-06-17 042441](https://github.com/fudan-generative-vision/hallo/assets/93273688/32728411-7c39-42f3-9125-3734e800e985)

what should i do ?

**Comment by Rokkonrol** [comment]
Firstly, ensure that you aren't running out of storage during the installation (nearly 30GB.) 

1. Delete the installation and reinstall. If the same error persists, open a terminal and navigate to the folder where `hallo` is installed (usually `pinokio\api\hallo.git\app`)
2.  Activate the virtual environment via `.\env\Scripts\activate`
3. `pip3 install -r requirements.txt`. Afterwards, try to start hallo again
4. If the same error persists, force reinstall the requirements via `pip3 install -r requirements.txt --force-reinstall` and then try to start hallo
5. If you're still getting the same error, I suggest installing hallo using the instructions on the official repo page: https://github.com/fudan-generative-vision/hallo
