### ISSUE TITLE
When cloning a model using git clone, I encountered an error =>The download of `hallo/net.pth` failed.

### ISSUE THREAD

**Issue by Samge0** [fudan-generative-vision/hallo#58]
LFS is confirmed to be installed and working properly, and a proxy was also used for the download.

run:
```shell
git lfs clone https://huggingface.co/fudan-generative-ai/hallo pretrained_models
```

error:
```text
WARNING: git lfs clone is deprecated and will not be updated
with new flags from git clone

git clone has been updated in upstream Git to have comparable
speeds to git lfs clone.
Cloning into 'pretrained_models'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 52 (delta 6), reused 0 (delta 0), pack-reused 4 (from 1)
Unpacking objects: 100% (52/52), 11.47 KiB | 25.00 KiB/s, done.
expected OID e886a9610b71a0f05a4cc65b4eb5bf3cebabfc75b06f8818c40ac225e69a0015, got 974a61a7c6ef1748966794cfba0f2535831680593c781791e671f49dad3c7300 after 4850540707 bytes written
Failed to fetch some objects from 'https://huggingface.co/fudan-generative-ai/hallo.git/info/lfs'
```
![image](https://github.com/fudan-generative-vision/hallo/assets/17336101/3e91323d-a387-48f4-b9a8-0e2e23f74b1d)

when I run the hallo demo, 
```shell
python scripts/inference.py --source_image examples/reference_images/1.jpg --driving_audio examples/driving_audios/1.wav
```

I got that:
```text
INFO:audio_separator.separator.separator:Starting separation process for audio_file_path: examples/driving_audios/1.wav
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:07<00:00, 2.43s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 4.48it/s]
INFO:audio_separator.separator.separator:Saving Vocals stem to 1_(Vocals)_Kim_Vocal_2.wav...
INFO:audio_separator.separator.separator:Clearing input audio file paths, sources and stems...
INFO:audio_separator.separator.separator:Separation duration: 00:00:09
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
INFO:hallo.models.unet_3d:loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5/unet ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from pretrained_models/motion_module/mm_sd_v15_v2.ckpt
INFO:hallo.models.unet_3d:Loaded 453.20928M-parameter motion module
Traceback (most recent call last):
File "/app/scripts/inference.py", line 372, in
inference_process(command_line_args)
File "/app/scripts/inference.py", line 244, in inference_process
torch.load(
File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

```
![image](https://github.com/fudan-generative-vision/hallo/assets/17336101/6fa6f72b-919d-4b40-8d86-b365a60f1a09)

**Comment by Samge0** [comment]
According to the log file, it was found that the download of the file `hallo/net.pth` failed.
Manually download the file and replace it.

log:
```text
git-lfs/3.5.1 (GitHub; windows amd64; go 1.21.7; git e237bb3a)
git version 2.45.2.windows.1

$ git-lfs.exe filter-process
Error downloading object: hallo/net.pth (e886a96): Smudge error: Error downloading hallo/net.pth (e886a9610b71a0f05a4cc65b4eb5bf3cebabfc75b06f8818c40ac225e69a0015): expected OID e886a9610b71a0f05a4cc65b4eb5bf3cebabfc75b06f8818c40ac225e69a0015, got 974a61a7c6ef1748966794cfba0f2535831680593c781791e671f49dad3c7300 after 4850540707 bytes written

expected OID e886a9610b71a0f05a4cc65b4eb5bf3cebabfc75b06f8818c40ac225e69a0015, got 974a61a7c6ef1748966794cfba0f2535831680593c781791e671f49dad3c7300 after 4850540707 bytes written
github.com/git-lfs/git-lfs/v3/errors.New
	github.com/git-lfs/git-lfs/v3/errors/errors.go:62
github.com/git-lfs/git-lfs/v3/tq.(*basicDownloadAdapter).download
	github.com/git-lfs/git-lfs/v3/tq/basic_download.go:249
github.com/git-lfs/git-lfs/v3/tq.(*basicDownloadAdapter).DoTransfer
	github.com/git-lfs/git-lfs/v3/tq/basic_download.go:96
github.com/git-lfs/git-lfs/v3/tq.(*adapterBase).worker
	github.com/git-lfs/git-lfs/v3/tq/adapterbase.go:183
runtime.goexit
	runtime/asm_amd64.s:1650
Error downloading hallo/net.pth (e886a9610b71a0f05a4cc65b4eb5bf3cebabfc75b06f8818c40ac225e69a0015)
github.com/git-lfs/git-lfs/v3/errors.newWrappedError
	github.com/git-lfs/git-lfs/v3/errors/types.go:229
github.com/git-lfs/git-lfs/v3/errors.Wrapf
	github.com/git-lfs/git-lfs/v3/errors/errors.go:85
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).downloadFile
	github.com/git-lfs/git-lfs/v3/lfs/gitfilter_smudge.go:134
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).Smudge
	github.com/git-lfs/git-lfs/v3/lfs/gitfilter_smudge.go:85
github.com/git-lfs/git-lfs/v3/commands.smudge
	github.com/git-lfs/git-lfs/v3/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/v3/commands.filterCommand
	github.com/git-lfs/git-lfs/v3/commands/command_filter_process.go:131
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-lfs/git-lfs/v3/commands.Run
	github.com/git-lfs/git-lfs/v3/commands/run.go:154
main.main
	github.com/git-lfs/git-lfs/v3/git-lfs.go:34
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
Smudge error
github.com/git-lfs/git-lfs/v3/errors.newWrappedError
	github.com/git-lfs/git-lfs/v3/errors/types.go:229
github.com/git-lfs/git-lfs/v3/errors.NewSmudgeError
	github.com/git-lfs/git-lfs/v3/errors/types.go:315
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).Smudge
	github.com/git-lfs/git-lfs/v3/lfs/gitfilter_smudge.go:102
github.com/git-lfs/git-lfs/v3/commands.smudge
	github.com/git-lfs/git-lfs/v3/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/v3/commands.filterCommand
	github.com/git-lfs/git-lfs/v3/commands/command_filter_process.go:131
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-lfs/git-lfs/v3/commands.Run
	github.com/git-lfs/git-lfs/v3/commands/run.go:154
main.main
	github.com/git-lfs/git-lfs/v3/git-lfs.go:34
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650

Current time in UTC:
2024-06-19 07:07:43

Environment:
LocalWorkingDir=F:\Space\PRO\ai\hallo\.cache\hallo
LocalGitDir=F:\Space\PRO\ai\hallo\.cache\hallo\.git
LocalGitStorageDir=F:\Space\PRO\ai\hallo\.cache\hallo\.git
LocalMediaDir=F:\Space\PRO\ai\hallo\.cache\hallo\.git\lfs\objects
LocalReferenceDirs=
TempDir=F:\Space\PRO\ai\hallo\.cache\hallo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=F:\Space\PRO\ai\hallo\.cache\hallo\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_DIR=F:/Space/PRO/ai/hallo/.cache/hallo/.git
GIT_EXEC_PATH=D:/APP/Git/mingw64/libexec/git-core

Client IP addresses:
fe80::4231:5242:9a9b:a615 192.168.50.48
fe80::9156:3313:e61b:bf7e 172.22.96.1
fe80::e57e:9d47:61e8:239 172.24.96.1

```

**Comment by Samge0** [comment]
After manually downloading the file, the issue was resolved.
![image](https://github.com/fudan-generative-vision/hallo/assets/17336101/450a6279-9f3e-4534-8074-24c0a8647fc7)
