### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 4

### ISSUE THREAD

**Issue by Song367** [fudan-generative-vision/hallo#68]
pipeline_output = pipeline(
            ref_image=pixel_values_ref_img,
            audio_tensor=audio_tensor,
            face_emb=source_image_face_emb,
            face_mask=source_image_face_region,
            pixel_values_full_mask=source_image_full_mask,
            pixel_values_face_mask=source_image_face_mask,
            pixel_values_lip_mask=source_image_lip_mask,
            width=1024,
            height=1024,
            video_length=clip_length,
            num_inference_steps=config.inference_steps,
            guidance_scale=config.cfg_scale,
            generator=generator,
            motion_scale=motion_scale,
        )

change: 
width=1024
height=1024

Traceback (most recent call last):
  File "F:\workplace\hallo-webui\scripts\inference.py", line 424, in <module>
    inference_process(
  File "F:\workplace\hallo-webui\scripts\inference.py", line 364, in inference_process
    pipeline_output = pipeline(
  File "F:\workplace\hallo-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\workplace\hallo-webui\hallo\animate\face_animate.py", line 401, in __call__
    noise_pred = self.denoising_unet(
  File "F:\workplace\hallo-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\workplace\hallo-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\workplace\hallo-webui\hallo\models\unet_3d.py", line 605, in forward
    sample = sample + mask_cond_fea
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 4

**Comment by xumingw** [comment]
you should change resolution setting in configs/inference/default.yaml instead of code
