### ISSUE TITLE
face_emb = face["embedding"]  KeyError: 'embedding'

### ISSUE THREAD

**Issue by gtfaiwxm** [fudan-generative-vision/hallo#87]
face, dict_keys(['bbox', 'kps', 'det_score', 'landmark_2d_106', 'gender', 'age']) #这是打印的face的关键字，没有embedding
Traceback (most recent call last):
  File "/mnt/e/my_project/hallo/scripts/inference.py", line 374, in <module>
    inference_process(command_line_args)
  File "/mnt/e/my_project/hallo/scripts/inference.py", line 162, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "/home/miniconda3/envs/hallo/lib/python3.10/site-packages/hallo/datasets/image_processor.py", line 139, in preprocess
    face_emb = face["embedding"]
KeyError: 'embedding'

**Comment by subazinga** [comment]
Could you share the full log?

**Comment by gtfaiwxm** [comment]
Applied providers: ['AzureExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'AzureExecutionProvider': {}}
find model: ./pretrained_models/face_analysis/models/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['AzureExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'AzureExecutionProvider': {}}
find model: ./pretrained_models/face_analysis/models/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['AzureExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'AzureExecutionProvider': {}}
find model: ./pretrained_models/face_analysis/models/scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
faces, dict_keys(['bbox', 'kps', 'det_score', 'landmark_2d_106', 'gender', 'age'])
Traceback (most recent call last):
  File "/mnt/e/my_project/hallo/scripts/inference.py", line 374, in <module>
    inference_process(command_line_args)
  File "/mnt/e/my_project/hallo/scripts/inference.py", line 162, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "/home/gtf/miniconda3/envs/hallo/lib/python3.10/site-packages/hallo/datasets/image_processor.py", line 139, in preprocess
    face_emb = face["embedding"]
KeyError: 'embedding'

**Comment by xumingw** [comment]
Have  you test any other ref image? it may be caused by failure when detect face in reference image

**Comment by gtfaiwxm** [comment]
When I test all the ref image, the error is same.

**Comment by Superanke** [comment]
I got the same error. 
Full log is here:

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./pretrained_models/face_analysis\models\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./pretrained_models/face_analysis\models\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./pretrained_models/face_analysis\models\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./pretrained_models/face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
WARNING:py.warnings:d:\pinokio\api\hallo.git\app\env\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

Traceback (most recent call last):
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "d:\pinokio\api\hallo.git\app\env\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "d:\pinokio\api\hallo.git\app\scripts\app.py", line 47, in predict
    return inference_process(args)
  File "d:\pinokio\api\hallo.git\app\scripts\inference.py", line 162, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "d:\pinokio\api\hallo.git\app\hallo\datasets\image_processor.py", line 127, in preprocess
    face_emb = face["embedding"]
KeyError: 'embedding'

**Comment by Superanke** [comment]
> When I test all the ref image, the error is same.

Hello there! Did you fix this error? Need some solutions. Thanks
