### ISSUE TITLE
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/.zip

### ISSUE THREAD

**Issue by runshouse** [fudan-generative-vision/hallo#93]
Getting this error when I run inference.py. Any suggestions?

**Comment by AricGamma** [comment]
Could you please show the total logs when this error occured?

**Comment by runshouse** [comment]
> Could you please show the total logs when this error occured?

Yes see below:

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.2+cu118 with CUDA 1108 (you have 2.2.2+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-06-25 04:16:08.523496: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-25 04:16:08.523565: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-25 04:16:08.526537: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-25 04:16:10.230914: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
download_path: ./pretrained_models/face_analysis/models/
Downloading ./pretrained_models/face_analysis/models/.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/.zip...
Traceback (most recent call last):
  File "/content/hallo/scripts/inference.py", line 376, in <module>
    inference_process(command_line_args)
  File "/content/hallo/scripts/inference.py", line 157, in inference_process
    with ImageProcessor(img_size, face_analysis_model_path) as image_processor:
  File "/usr/local/lib/python3.10/dist-packages/hallo-0.1.0-py3.10.egg/hallo/datasets/image_processor.py", line 97, in __init__
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "/usr/local/lib/python3.10/dist-packages/insightface/utils/storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "/usr/local/lib/python3.10/dist-packages/insightface/utils/storage.py", line 17, in download
    download_file(model_url,
  File "/usr/local/lib/python3.10/dist-packages/insightface/utils/download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/.zip
```

**Comment by AricGamma** [comment]
It seems that there are no models file under `pretrained_models/face_analysis/models`. 
You can follow this section to download all models required. https://github.com/fudan-generative-vision/hallo?tab=readme-ov-file#-download-pretrained-models

**Comment by runshouse** [comment]
> It seems that there are no models file under `pretrained_models/face_analysis/models`. You can follow this section to download all models required. https://github.com/fudan-generative-vision/hallo?tab=readme-ov-file#-download-pretrained-models

thank you. now running into a different error so will mark this as closed
