### ISSUE TITLE
RuntimeError: operator torchvision::nms does not exist

### ISSUE THREAD

**Issue by runshouse** [fudan-generative-vision/hallo#98]
When I run inference.py, I receive this error:

```
Traceback (most recent call last):
  File "/content/hallo/scripts/inference.py", line 40, in <module>
    from hallo.datasets.audio_processor import AudioProcessor
  File "/usr/local/lib/python3.10/dist-packages/hallo-0.1.0-py3.10.egg/hallo/datasets/audio_processor.py", line 19, in <module>
  File "/usr/local/lib/python3.10/dist-packages/hallo-0.1.0-py3.10.egg/hallo/utils/util.py", line 76, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 467, in inner
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/usr/local/lib/python3.10/dist-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
```

Any ideas on how to debug?

**Comment by JaimeIsMe** [comment]
I'm having the same issues. How did you solve it?
